name: Build Native Executable

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-native:
    runs-on: ubuntu-latest
    container: amazoncorretto:21-al2023

    steps:
      - name: Install system dependencies
        run: dnf install -y tar gzip git libcurl-devel openssl-devel

      - uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Test and build native executable
        run: ./gradlew nativeTest assembleReleaseBinary --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pakmc
          path: build/release/pakmc
